
[Accessories]

	[Accessories.WhiteFlag]
		#Ratio of damage ignored while being attacked.
		#Range: 0.01 ~ 0.99
		damage_received_reduction = 0.2
		#Ratio of damage ignored when attacking.
		#Range: 0.01 ~ 0.99
		damage_dealt_penalty = 0.6
		#Price the villager will pay for this accessory (requires world/game restart).
		#Range: 1 ~ 32
		trade_price = 7
		#Chance for White Flag to spawn in any village chest.
		#Range: 0.0 ~ 1.0
		spawn_chance = 0.15
		#Determines which chests should contain White Flag.
		#Supports 'regular expressions' when text starts with {regex} prefix.
		loot_table_ids = ["minecraft:chests/village/village_weaponsmith", "minecraft:chests/village/village_toolsmith", "minecraft:chests/village/village_armorer", "minecraft:chests/village/village_armorer", "minecraft:chests/village/village_cartographer", "minecraft:chests/village/village_mason", "minecraft:chests/village/village_shepherd", "minecraft:chests/village/village_butcher", "minecraft:chests/village/village_fletcher", "minecraft:chests/village/village_fisher", "minecraft:chests/village/village_tannery", "minecraft:chests/village/village_temple", "minecraft:chests/village/village_desert_house", "minecraft:chests/village/village_plains_house", "minecraft:chests/village/village_taiga_house", "minecraft:chests/village/village_snowy_house", "minecraft:chests/village/village_savanna_house"]

	[Accessories.TamedPotatoBeetle]
		#Chance to double crops when harvesting.
		#Range: 0.0 ~ 1.0
		double_crops_chance = 0.25
		#Price the villager will pay for this accessory (requires world/game restart).
		#Range: 1 ~ 32
		trade_price = 7
		#Chance for Tamed Potato Beetle to drop when harvesting.
		#Range: 0.0 ~ 1.0
		drop_chance = 0.002
		#Chance multiplier when harvesting potatoes.
		#Range: 1.0 ~ 10.0
		potato_multiplier = 2.5

	[Accessories.SecretIngredient]
		#Duration penalty for created enhanced potions.
		#Range: 0.0 ~ 0.99
		potion_duration_penalty = 0.6
		#Extra potion level for created enhanced potions.
		#Range: 1 ~ 10
		potion_extra_amplifier = 1
		#Price the villager will pay for this accessory (requires world/game restart).
		#Range: 1 ~ 32
		trade_price = 7
		#Chance for Secret Ingredient to drop from Witch.
		#Range: 0.0 ~ 1.0
		drop_chance = 0.025

	[Accessories.OverworldRune]
		#Extra multiplier for number of items acquired from chests.
		#Range: 0.0 ~ 10.0
		chest_size_bonus = 1.5
		#Luck bonus when fishing.
		#Range: 1 ~ 10
		fishing_luck = 4
		#Time reduction multiplier when fishing.
		#Range: 0.01 ~ 0.99
		time_multiplier = 0.5
		#Bonus health, damage, movement speed and jump height for tamed animals.
		#Range: 0.0 ~ 10.0
		animal_bonus = 0.25
		#Chance to spawn twins when breeding animals.
		#Range: 0.0 ~ 1.0
		twins_chance = 0.3
		#Chance to drop extra items when mining stone.
		#Range: 0.0 ~ 1.0
		extra_loot_chance = 0.04
		#Duration penalty for created enhanced potions.
		#Range: 0.0 ~ 0.99
		potion_duration_penalty = 0.5
		#Extra potion level for created enhanced potions.
		#Range: 1 ~ 10
		potion_extra_amplifier = 1
		#Chance to double crops when harvesting.
		#Range: 0.0 ~ 1.0
		double_crops_chance = 0.3
		#Ratio of damage ignored while being attacked.
		#Range: 0.01 ~ 0.99
		damage_received_reduction = 0.0625
		#Price the villager will pay for this accessory (requires world/game restart).
		#Range: 1 ~ 32
		trade_price = 17

	[Accessories.LuckyRock]
		#Chance to drop extra items when mining stone.
		#Range: 0.0 ~ 1.0
		extra_loot_chance = 0.03
		#Price the villager will pay for this accessory (requires world/game restart).
		#Range: 1 ~ 32
		trade_price = 7
		#Chance for Lucky Rock to drop when mining stone.
		#Range: 0.0 ~ 1.0
		drop_chance = 5.0E-4

	[Accessories.IdolOfFertility]
		#Chance to spawn twins when breeding animals.
		#Range: 0.0 ~ 1.0
		twins_chance = 0.25
		#Price the villager will pay for this accessory (requires world/game restart).
		#Range: 1 ~ 32
		trade_price = 7
		#Chance for Idol of Fertility to drop when breeding animals.
		#Range: 0.0 ~ 1.0
		drop_chance = 0.01

	[Accessories.CertificateOfTaming]
		#Bonus health, damage, movement speed and jump height for tamed animals.
		#Range: 0.0 ~ 10.0
		animal_bonus = 0.2
		#Price the villager will pay for this accessory (requires world/game restart).
		#Range: 1 ~ 32
		trade_price = 7
		#Chance for Certificate of Taming to drop when taming animals.
		#Range: 0.0 ~ 1.0
		drop_chance = 0.04

	[Accessories.AnglersTrophy]
		#Luck bonus when fishing.
		#Range: 1 ~ 10
		fishing_luck = 3
		#Time reduction multiplier when fishing.
		#Range: 0.01 ~ 0.99
		time_multiplier = 0.4
		#Price the villager will pay for this accessory (requires world/game restart).
		#Range: 1 ~ 32
		trade_price = 7
		#Chance to drop Angler's Trophy when fishing.
		#Range: 0.0 ~ 1.0
		drop_chance = 0.015

	[Accessories.AdventurersGuide]
		#Extra multiplier for number of items acquired from chests.
		#Range: 0.0 ~ 10.0
		chest_size_bonus = 1.2
		#Chance for Adventurer's Guide to spawn in any chest.
		#Range: 0.0 ~ 1.0
		spawn_chance = 0.025
		#Price the villager will pay for this accessory (requires world/game restart).
		#Range: 1 ~ 32
		trade_price = 7

[Boosters]
	#Chance for random booster to spawn in any Nether chest.
	#Range: 0.0 ~ 1.0
	chest_chance = 0.1
	#Chance for random booster to drop from any Nether mob.
	#Range: 0.0 ~ 1.0
	mob_chance = 0.001

	[Boosters.OwlFeather]
		#Extra experience multiplier from all sources.
		#Range: 0.01 ~ 10.0
		experience_extra_multiplier = 0.15
		#Chance for Owl Feather to drop from Vex.
		#Range: 0.0 ~ 1.0
		drop_chance = 0.1

	[Boosters.Horseshoe]
		#Extra luck bonus.
		#Range: 1 ~ 10
		luck = 1
		#Chance for Horseshoe to drop from Skeleton Horseman.
		#Range: 0.0 ~ 1.0
		drop_chance = 0.334

	[Boosters.GoldenHorseshoe]
		#Extra luck bonus.
		#Range: 1 ~ 10
		luck = 2

	[Boosters.GoldenDice]
		#Extra chance multiplier to drop accessories.
		#Range: 0.01 ~ 10.0
		extra_chance_multiplier = 0.4

	[Boosters.Dice]
		#Extra chance multiplier to drop accessories.
		#Range: 0.01 ~ 10.0
		extra_chance_multiplier = 0.2
		#Chance for Dice to drop from Guardian.
		#Range: 0.0 ~ 1.0
		drop_chance = 0.05

