
[general]
	#Enable that penguins drop fish (0 - 2 Raw Cod)
	dropFish = false
	#Penguins should drop experience?
	dropExp = true
	#Use the Darkosto skin variant by default?
	darkostoDefault = false

